avaliacao:
  build: .
  ports:
    - "3001:3000"
  environment:
    # MYSQL_ROOT_PASSWORD: root
    # MYSQL_ADDRESS: db
    RAILS_ENV: development
  volumes:
    - .:/app
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

